---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: budhaujjwal/todo-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: database
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: test123
            - name: DB_NAME
              value: todo_db
            - name: PORT
              value: "3001"
